### ISSUE TITLE
mismatch ocaml-tree-sitter vs tree-sitter for Swift grammar

### ISSUE THREAD

**Issue by aryx** [returntocorp/ocaml-tree-sitter-core#36]
There are a few errors when making in ocaml-tree-sitter-semgrep:
```
$ cd lang
$ ./test-lang switft
```
3 errors seems due to the use of emoji (I've created a separate issue for that, see #35 )
The last one seems due to the parsing of multiline comments.

If you take this simple hello.swift file:
```
class foo {
    var isFailed: Bool
    /* some comment */ let foo = 1
}
```
then it seems to parse correctly with tree-sitter (it's part of the testsuite in corpus/classes.txt in a slightly more complex form)
but failed after being through the ocaml-tree-sitter machinery.

here is the error:
```
$ cd swift
$ make
$ ./parse-swift ~/hello.swift
CST obtained from the tree-sitter parser:
source_file:
| top_level_statement:
|   global_declaration:
|   | class_declaration:
|   |   modifierless_class_declaration:
|   |   | "class"
|   |   | simple_identifier:
|   |   |   pat_9d0cc04:
|   |   | class_body:
|   |   |   "{"
|   |   |   !ERROR!:
|   |   |   | possibly_async_binding_pattern_kind:
|   |   |   |   binding_pattern_kind:
|   |   |   |   | "var"
|   |   |   | !ERROR!:
|   |   |   |   single_modifierless_property_declaration:
|   |   |   |   | no_expr_pattern_already_bound:
|   |   |   |   |   bound_identifier:
|   |   |   |   |   | simple_identifier:
|   |   |   |   |   |   pat_9d0cc04:
|   |   |   |   | type_annotation:
|   |   |   |   |   ":"
|   |   |   |   |   possibly_implicitly_unwrapped_type:
|   |   |   |   |   | type:
|   |   |   |   |   |   unannotated_type:
|   |   |   |   |   |   | user_type:
|   |   |   |   |   |   |   simple_user_type:
|   |   |   |   |   |   |   | simple_identifier:
|   |   |   |   |   |   |   |   pat_9d0cc04:
|   |   |   | multiline_comment:
|   |   |   | binding_pattern:
|   |   |   |   binding_pattern_kind:
|   |   |   |   | "let"
|   |   |   |   no_expr_pattern_already_bound:
|   |   |   |   | bound_identifier:
|   |   |   |   |   simple_identifier:
|   |   |   |   |   | pat_9d0cc04:
|   |   |   | eq_custom:
|   |   |   | integer_literal:
|   |   |   | semi:
|   |   |   "}"
| semi:
---
Recovered typed CST:
|   |   Global_decl
|   |   | Class_decl
|   |   |   | Choice_class_simple_id_opt_type_params_opt_COLON_inhe_specis_opt_type_consts_class_body
|   |   |   |   | Class
|   |   |   |   | class
|   |   |   |   | Pat_9d0cc04
|   |   |   |   | foo
|   |   |   |   | "{"
|   |   |   |   | "}"
|   |   ""
total lines: 5
error lines: 3
error count: 1
success: 40.00%
Error: File /home/pad/hello.swift, line 2, character 4 to line 4, character 0:
class foo {
    var isFailed: Bool
    /* some comment */ let foo = 1
}

parent: class_body, left sibling: "{", first child: possibly_async_binding_pattern_kind
node type: ERROR
children: [
  possibly_async_binding_pattern_kind
  ERROR
  multiline_comment
  binding_pattern
  eq_custom
  integer_literal
  semi
]
Unrecognized construct
```

**Comment by aryx** [comment]
I think the issue may be due to the use of     $.multiline_comment,
both in the extras: section, and in actual rules as in:
    _class_member_separator: ($) => choice($._semi, $.multiline_comment),

which might confuse ocaml-tree-sitter.

**Comment by mjambon** [comment]
The problem is that the rule `multiline_comment` is declared an extra (meaning it can occur anywhere in the tree as comments do) but [also occurs within a specific rule](https://github.com/alex-pinkus/tree-sitter-swift/blob/33948c72fa206d2040cfe0b213d29d5739090ac6/grammar.js#L1359).

There may be two kinds of solutions:
* modify the grammar and/or scanner so as to create an alias for the rule `multiline_comment`. Then, use one name a normal rule and the other as an extra. Maybe this would require dealing with a conflict between the expected comment and the same comment treated as an extra, I don't know.
* address this automatically in ocaml-tree-sitter in the pass that rewrites the grammar. It could be done with the alias() construct and it would look like `alias($.multiline_comment, $.multiline_comment_explicit)`. The effect will be that `$.multiline_comment_explicit` will occur in the CST instead of `$.multiline_comment` at this particular spot, avoiding the confusion with extras that need to be removed from the CST.
